"""
ILA — PostgreSQL Loader
scripts/load_into_postgres.py

Reads the mock_data.json generated by generate_mock_data.py and inserts
everything into PostgreSQL using SQLAlchemy (same ORM the app uses).

Flow:
  1. Read mock_data.json
  2. Create all tables (if not exist)
  3. Insert in dependency order:
       users → sources → keywords → entities → aliases → events → entity_events → alerts

Usage:
  # Make sure PostgreSQL is running (docker compose up postgres)
  python scripts/load_into_postgres.py

  # Or with a custom DB URL:
  DATABASE_URL=postgresql://user:pass@localhost:5432/ila_db python scripts/load_into_postgres.py

  # Reset and reload (drops all data first):
  RESET=true python scripts/load_into_postgres.py

By default the loader is idempotent and preserves existing rows. Use RESET=true
only when you explicitly want a clean reload.
"""

import json
import os
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

# ── Ensure app package is on path ─────────────────────────────────────────────
# Resolve project root (repo root) so `backend/` is found from anywhere.
# File is at <repo>/infra/scripts/..., so parents[2] is the repo root.
ROOT = Path(__file__).resolve().parent.parent.parent
# Look specifically inside the backend folder for the 'app' module
BACKEND_PATH = ROOT / "backend"
if str(BACKEND_PATH) not in sys.path:
    sys.path.insert(0, str(BACKEND_PATH))
import importlib
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

# Ensure we can import the 'app' package. Try a few likely locations under backend.
POSSIBLE_APP_PATHS = [
    BACKEND_PATH,
    BACKEND_PATH / "src",
    BACKEND_PATH / "app",
]

for p in POSSIBLE_APP_PATHS:
    p_str = str(p)
    if p_str not in sys.path and p.exists():
        sys.path.insert(0, p_str)

# Import directly from app.models (which triggers the __init__.py in the app package)
try:
    from app.models import (
        Base, User, Source, Keyword, Entity, EntityAlias,
        RawEvent, EntityEvent, RiskAlert, EvidencePackage
    )
except Exception:
    # Final attempt: try importlib to surface a clearer error if it still fails
    importlib.invalidate_caches()
    try:
        mod = importlib.import_module('app.models')
        Base = getattr(mod, 'Base')
        User = getattr(mod, 'User')
        Source = getattr(mod, 'Source')
        Keyword = getattr(mod, 'Keyword')
        Entity = getattr(mod, 'Entity')
        EntityAlias = getattr(mod, 'EntityAlias')
        RawEvent = getattr(mod, 'RawEvent')
        EntityEvent = getattr(mod, 'EntityEvent')
        RiskAlert = getattr(mod, 'RiskAlert')
        EvidencePackage = getattr(mod, 'EvidencePackage')
    except Exception as e:
        raise ImportError("Could not import 'app.models'. Ensure the backend/app package is on PYTHONPATH.") from e
# ── Config ────────────────────────────────────────────────────────────────────
MOCK_DATA_PATH = Path(__file__).parent / "mock_data.json"
RESET = os.environ.get("RESET", "false").lower() == "true" or "--reset" in sys.argv or "-r" in sys.argv

BATCH_SIZE = 100   # insert in batches to avoid memory issues


# ── Helpers ───────────────────────────────────────────────────────────────────

def load_env_file(env_path: Path) -> None:
    """Load simple KEY=VALUE pairs from a .env file if present."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def build_database_url() -> str:
    """Return DATABASE_URL or build it from POSTGRES_* environment variables."""
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        return database_url

    postgres_host = os.getenv("POSTGRES_HOST")
    postgres_port = os.getenv("POSTGRES_PORT")
    postgres_db = os.getenv("POSTGRES_DB")
    postgres_user = os.getenv("POSTGRES_USER")
    postgres_password = os.getenv("POSTGRES_PASSWORD")

    if all([postgres_host, postgres_port, postgres_db, postgres_user, postgres_password]):
        return (
            f"postgresql://{postgres_user}:{postgres_password}"
            f"@{postgres_host}:{postgres_port}/{postgres_db}"
        )

    raise ValueError(
        "DATABASE_URL is not set and the POSTGRES_* variables are incomplete. "
        "Set DATABASE_URL or provide POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, "
        "POSTGRES_USER, and POSTGRES_PASSWORD before running this script."
    )


load_env_file(ROOT / ".env")
load_env_file(ROOT.parent / ".env")
DATABASE_URL = build_database_url()

def parse_dt(s):
    """Parse ISO datetime string, return None if falsy."""
    if not s:
        return None
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def log(msg: str):
    """Simple timestamped logger."""
    ts = datetime.now(timezone.utc).strftime("%H:%M:%S")
    try:
        print(f"[{ts}] {msg}")
    except UnicodeEncodeError:
        encoding = sys.stdout.encoding or 'ascii'
        safe_msg = msg.encode(encoding, errors='replace').decode(encoding)
        print(f"[{ts}] {safe_msg}")


def batch_insert(session, model, records: list, batch_size: int = BATCH_SIZE):
    """Insert records in batches, return count inserted."""
    total = 0
    for i in range(0, len(records), batch_size):
        batch = records[i : i + batch_size]
        session.bulk_save_objects([model(**r) for r in batch])
        session.flush()
        total += len(batch)
    return total


# ── Table Setup ───────────────────────────────────────────────────────────────

def setup_tables(engine, reset: bool = False):
    """Create tables (or drop+recreate if RESET=true)."""
    if reset:
        log("⚠️  RESET=true — dropping all tables and recreating schema...")
        with engine.begin() as conn:
            conn.execute(text("DROP SCHEMA public CASCADE;"))
            conn.execute(text("CREATE SCHEMA public;"))
            conn.execute(text("GRANT ALL ON SCHEMA public TO public;"))
            # Make sure public role has usage on schema public
            conn.execute(text("GRANT USAGE ON SCHEMA public TO public;"))
        log("   Schema reset complete.")
    log("Creating tables (if not exist)...")
    try:
        Base.metadata.create_all(engine)
        log("   Tables ready.")
    except Exception as e:
        log(f"   Note: create_all had an issue (might be index/table mismatch): {e}")
        log("   Proceeding anyway as tables may already exist.")


# ── Loaders ───────────────────────────────────────────────────────────────────

def load_users(session, records: list) -> dict:
    """Insert users. Returns {username → id} map."""
    log(f"Loading {len(records)} users...")
    id_map = {}
    for r in records:
        existing = session.query(User).filter(
            (User.username == r["username"]) | (User.email == r["email"])
        ).first()
        if existing:
            existing.username = r["username"]
            existing.email = r["email"]
            existing.hashed_password = r["hashed_password"]
            existing.full_name = r.get("full_name")
            existing.role = r.get("role", "analyst")
            existing.is_active = r.get("is_active", True)
            id_map[r["username"]] = existing.id
        else:
            user = User(
                id=r["id"],
                username=r["username"],
                email=r["email"],
                hashed_password=r["hashed_password"],
                full_name=r.get("full_name"),
                role=r.get("role", "analyst"),
                is_active=r.get("is_active", True),
            )
            session.add(user)
            id_map[r["username"]] = r["id"]
    session.flush()
    log(f"   ✓ {len(records)} users loaded")
    return id_map


def load_sources(session, records: list) -> dict:
    """Insert data sources. Returns {name → id} map."""
    log(f"Loading {len(records)} sources...")
    id_map = {}
    for r in records:
        src = Source(
            id=r["id"],
            name=r["name"],
            source_type=r["source_type"],
            tier=r["tier"],
            url=r.get("url"),
            description=r.get("description"),
            is_active=r.get("is_active", True),
            reliability_multiplier=r.get("reliability_multiplier", 1.0),
            crawl_interval_minutes=r.get("crawl_interval_minutes", 15),
            last_crawled_at=parse_dt(r.get("last_crawled_at")),
            event_count_today=r.get("event_count_today", 0),
        )
        session.merge(src)
        id_map[r["name"]] = r["id"]
    session.flush()
    log(f"   ✓ {len(records)} sources loaded")
    return id_map


def load_keywords(session, records: list) -> dict:
    """Insert keywords. Returns {word → id} map."""
    log(f"Loading {len(records)} keywords...")
    id_map = {}
    for r in records:
        existing = session.query(Keyword).filter(
            Keyword.word == r["word"],
            Keyword.category == r.get("category")
        ).first()
        if existing:
            existing.language = r.get("language", "en")
            existing.is_active = r.get("is_active", True)
            existing.match_count = r.get("match_count", 0)
            id_map[r["word"]] = existing.id
        else:
            kw = Keyword(
                id=r["id"],
                word=r["word"],
                category=r.get("category"),
                language=r.get("language", "en"),
                is_active=r.get("is_active", True),
                match_count=r.get("match_count", 0),
            )
            session.add(kw)
            id_map[r["word"]] = r["id"]
    session.flush()
    log(f"   ✓ {len(records)} keywords loaded")
    return id_map


def load_entities(session, records: list) -> set:
    """Insert entities. Returns set of inserted entity IDs."""
    log(f"Loading {len(records)} entities...")
    inserted_ids = set()
    for i in range(0, len(records), BATCH_SIZE):
        batch = records[i : i + BATCH_SIZE]
        for r in batch:
            # Strip internal helper fields that don't exist in the model
            entity = Entity(
                id=r["id"],
                entity_type=r["entity_type"],
                primary_identifier=r["primary_identifier"],
                display_name=r.get("display_name"),
                risk_score=r.get("risk_score", 0.0),
                risk_level=r.get("risk_level", "low"),
                influence_score=r.get("influence_score", 0.0),
                anomaly_score=r.get("anomaly_score", 0.0),
                sentiment_avg=r.get("sentiment_avg", 0.0),
                event_count=r.get("event_count", 0),
                first_seen=parse_dt(r.get("first_seen")),
                last_seen=parse_dt(r.get("last_seen")),
                is_flagged=r.get("is_flagged", False),
                investigation_notes=r.get("investigation_notes"),
                risk_factors=r.get("risk_factors", []),
                metadata_=r.get("metadata_", {}),
            )
            session.merge(entity)
            inserted_ids.add(r["id"])
        session.flush()
        log(f"   ... {min(i + BATCH_SIZE, len(records))}/{len(records)} entities")
    log(f"   ✓ {len(records)} entities loaded")
    return inserted_ids


def load_aliases(session, records: list):
    """Insert entity aliases."""
    log(f"Loading {len(records)} entity aliases...")
    entity_ids = {r["entity_id"] for r in records}
    alias_values = {r["alias_value"] for r in records}
    
    existing_aliases = set()
    if records:
        existing_rows = (
            session.query(EntityAlias.entity_id, EntityAlias.alias_value)
            .filter(EntityAlias.entity_id.in_(list(entity_ids)))
            .filter(EntityAlias.alias_value.in_(list(alias_values)))
            .all()
        )
        existing_aliases = {(row[0], row[1]) for row in existing_rows}

    inserted_count = 0
    updated_count = 0
    
    for i in range(0, len(records), BATCH_SIZE):
        batch = records[i : i + BATCH_SIZE]
        for r in batch:
            if (r["entity_id"], r["alias_value"]) in existing_aliases:
                existing = session.query(EntityAlias).filter(
                    EntityAlias.entity_id == r["entity_id"],
                    EntityAlias.alias_value == r["alias_value"]
                ).first()
                if existing:
                    existing.alias_type = r["alias_type"]
                    existing.platform = r.get("platform")
                    existing.confidence = r.get("confidence", 1.0)
                    existing.resolution_method = r.get("resolution_method", "exact")
                    existing.is_verified = r.get("is_verified", False)
                    updated_count += 1
            else:
                alias = EntityAlias(
                    id=r["id"],
                    entity_id=r["entity_id"],
                    alias_type=r["alias_type"],
                    alias_value=r["alias_value"],
                    platform=r.get("platform"),
                    confidence=r.get("confidence", 1.0),
                    resolution_method=r.get("resolution_method", "exact"),
                    is_verified=r.get("is_verified", False),
                )
                session.merge(alias)
                inserted_count += 1
        session.flush()
    log(f"   ✓ {inserted_count} aliases loaded + {updated_count} aliases updated")


def load_events(session, records: list) -> dict:
    """
    Insert raw events.
    Also builds entity_events (the many-to-many link) from extracted_entities
    and the _person_entity_id helper field in mock data.

    Returns {event_id → entity_id} map for alert linking.
    """
    log(f"Loading {len(records)} raw events...")
    entity_event_records = []

    for i in range(0, len(records), BATCH_SIZE):
        batch = records[i : i + BATCH_SIZE]
        for r in batch:
            # Strip helper fields without mutating the original record.
            person_entity_id = r.get("_person_entity_id")

            event = RawEvent(
                id=r["id"],
                source_id=r["source_id"],
                external_id=r.get("external_id"),
                content=r["content"],
                content_language=r.get("content_language", "unknown"),
                translated_content=r.get("translated_content"),
                url=r.get("url"),
                author_handle=r.get("author_handle"),
                platform=r.get("platform"),
                published_at=parse_dt(r.get("published_at")),
                is_processed=r.get("is_processed", False),
                is_duplicate=r.get("is_duplicate", False),
                extracted_entities=r.get("extracted_entities", []),
                sentiment_score=r.get("sentiment_score"),
                anomaly_score=r.get("anomaly_score"),
                matched_keywords=r.get("matched_keywords", []),
                metadata_=r.get("metadata_", {}),
            )
            session.merge(event)

            # Create entity_event link if we have a person reference
            if person_entity_id:
                entity_event_records.append({
                    "id": str(uuid.uuid4()),
                    "entity_id": person_entity_id,
                    "event_id": r["id"],
                    "role": "mentioned",
                })
        session.flush()

    # Bulk insert entity_events
    log(f"   Creating {len(entity_event_records)} entity↔event links...")
    entity_ids = {r["entity_id"] for r in entity_event_records}
    event_ids = {r["event_id"] for r in entity_event_records}
    
    existing_links = set()
    if entity_event_records:
        existing_rows = (
            session.query(EntityEvent.entity_id, EntityEvent.event_id)
            .filter(EntityEvent.entity_id.in_(list(entity_ids)))
            .filter(EntityEvent.event_id.in_(list(event_ids)))
            .all()
        )
        existing_links = {(row[0], row[1]) for row in existing_rows}

    inserted_count = 0
    for i in range(0, len(entity_event_records), BATCH_SIZE):
        batch = entity_event_records[i : i + BATCH_SIZE]
        for r in batch:
            if (r["entity_id"], r["event_id"]) in existing_links:
                continue
            
            ee = EntityEvent(
                id=r["id"],
                entity_id=r["entity_id"],
                event_id=r["event_id"],
                role=r["role"],
            )
            session.merge(ee)
            inserted_count += 1
        session.flush()

    log(f"   ✓ {len(records)} events loaded + {inserted_count} new entity-event links created")


def load_alerts(session, records: list):
    """Insert risk alerts."""
    log(f"Loading {len(records)} risk alerts...")
    for i in range(0, len(records), BATCH_SIZE):
        batch = records[i : i + BATCH_SIZE]
        for r in batch:
            alert = RiskAlert(
                id=r["id"],
                entity_id=r["entity_id"],
                alert_type=r["alert_type"],
                title=r["title"],
                description=r.get("description"),
                risk_score=r["risk_score"],
                risk_level=r["risk_level"],
                status=r.get("status", "new"),
                trigger_event_id=r.get("trigger_event_id"),
                matched_pattern=r.get("matched_pattern"),
                risk_factors=r.get("risk_factors", []),
                evidence_data=r.get("evidence_data", {}),
                reviewed_by=r.get("reviewed_by"),
                reviewed_at=parse_dt(r.get("reviewed_at")),
                analyst_note=r.get("analyst_note"),
                created_at=parse_dt(r.get("created_at")),
            )
            session.merge(alert)
        session.flush()
    log(f"   ✓ {len(records)} alerts loaded")


# ── Verification ──────────────────────────────────────────────────────────────

def verify_load(session):
    """Run quick count queries to verify everything loaded."""
    log("\n📊 Load verification:")
    checks = [
        ("users",          "SELECT COUNT(*) FROM users"),
        ("sources",        "SELECT COUNT(*) FROM sources"),
        ("keywords",       "SELECT COUNT(*) FROM keywords"),
        ("entities",       "SELECT COUNT(*) FROM entities"),
        ("entity_aliases", "SELECT COUNT(*) FROM entity_aliases"),
        ("raw_events",     "SELECT COUNT(*) FROM raw_events"),
        ("entity_events",  "SELECT COUNT(*) FROM entity_events"),
        ("risk_alerts",    "SELECT COUNT(*) FROM risk_alerts"),
    ]
    for label, sql in checks:
        count = session.execute(text(sql)).scalar()
        status = "✓" if count > 0 else "⚠️"
        log(f"   {status} {label:20s}: {count:>5} rows")

    # Spot-check: highest risk entity
    result = session.execute(text(
        "SELECT primary_identifier, risk_score, risk_level FROM entities ORDER BY risk_score DESC LIMIT 1"
    )).fetchone()
    if result:
        log(f"\n   🔴 Highest-risk entity: {result[0]} | score={result[1]} | level={result[2]}")

    # Spot-check: alert type distribution
    result = session.execute(text(
        "SELECT alert_type, COUNT(*) FROM risk_alerts GROUP BY alert_type ORDER BY COUNT(*) DESC"
    )).fetchall()
    log("\n   Alert type distribution:")
    for row in result:
        log(f"     {row[0]:30s}: {row[1]}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    log("=" * 60)
    log("ILA Mock Data Loader")
    log("=" * 60)
    log(f"Database: {DATABASE_URL.split('@')[-1]}")  # hide credentials
    log(f"Data file: {MOCK_DATA_PATH}")
    log(f"Reset mode: {RESET}")
    log("")

    # Read mock data
    if not MOCK_DATA_PATH.exists():
        log("❌ mock_data.json not found!")
        log("   Run: python scripts/generate_mock_data.py first")
        sys.exit(1)

    log(f"Reading {MOCK_DATA_PATH.name}...")
    with open(MOCK_DATA_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    meta = data.get("meta", {})
    log(f"   Generated at: {meta.get('generated_at', 'unknown')}")
    for k, v in meta.get("counts", {}).items():
        log(f"   {k:12s}: {v}")
    log("")

    # Connect to DB
    log("Connecting to PostgreSQL...")
    engine = create_engine(
        DATABASE_URL,
        pool_pre_ping=True,
        echo=False,           # set True to see SQL
    )
    Session = sessionmaker(bind=engine)

    # Create tables without destroying existing data unless RESET=true.
    setup_tables(engine, reset=RESET)

    # Load data in dependency order
    log("\n📥 Loading data...")
    with Session() as session:
        try:
            load_users(session,    data.get("users",    []))
            load_sources(session,  data.get("sources",  []))
            load_keywords(session, data.get("keywords", []))
            load_entities(session, data.get("entities", []))
            load_aliases(session,  data.get("aliases",  []))
            load_events(session,   data.get("events",   []))
            load_alerts(session,   data.get("alerts",   []))

            log("\n💾 Committing transaction...")
            session.commit()
            log("   ✓ Committed!")

            verify_load(session)

        except Exception as e:
            log(f"\n❌ Error during load: {e}")
            session.rollback()
            raise

    log("\n" + "=" * 60)
    log("✅ Mock data loaded successfully!")
    log("   You can now start the FastAPI server and see data.")
    log("=" * 60)


if __name__ == "__main__":
    main()
