"""Create users table

Revision ID: 0f22131e3d37
Revises: 20260531_ipaddr_enum
Create Date: 2026-05-31 21:42:07.443807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f22131e3d37'
down_revision = '20260531_ipaddr_enum'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('entities'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'PHONE', 'IP_ADDRESS', 'EMAIL', 'UPI_ACCOUNT', 'SOCIAL_HANDLE', 'TELEGRAM', 'WEBSITE', 'IMEI', 'CRYPTO_WALLET', name='entitytype'), nullable=False),
    sa.Column('primary_identifier', sa.String(length=512), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('sentiment_avg', sa.Float(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_is_flagged'), 'entities', ['is_flagged'], unique=False)
    op.create_index('ix_entities_primary_identifier', 'entities', ['primary_identifier'], unique=False)
    op.create_index(op.f('ix_entities_risk_level'), 'entities', ['risk_level'], unique=False)
    op.create_index('ix_entities_risk_score', 'entities', ['risk_score'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.Enum('TELEGRAM_PUBLIC', 'TWITTER_X', 'RSS_NEWS', 'DARK_WEB', 'UPI_TRANSACTION', 'SOCIAL_MEDIA', 'FORUM', 'MOCK', name='sourcetype'), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', name='sourcetier'), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('reliability_multiplier', sa.Float(), nullable=True),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_count_today', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alias_type', sa.Enum('PERSON', 'PHONE', 'IP_ADDRESS', 'EMAIL', 'UPI_ACCOUNT', 'SOCIAL_HANDLE', 'TELEGRAM', 'WEBSITE', 'IMEI', 'CRYPTO_WALLET', name='entitytype'), nullable=False),
    sa.Column('alias_value', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.String(length=64), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'alias_value', name='uq_entity_alias')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index('ix_entity_aliases_value', 'entity_aliases', ['alias_value'], unique=False)
    op.create_table('evidence_packages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('generated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('entities_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('events_count', sa.Integer(), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('legal_disclaimer', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_evidence_packages_entity_id'), 'evidence_packages', ['entity_id'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('word', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', 'HINDI', 'URDU', 'BENGALI', 'TAMIL', 'TELUGU', 'MARATHI', 'PUNJABI', 'UNKNOWN', name='language'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'category', name='uq_keyword_category')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_language', sa.Enum('ENGLISH', 'HINDI', 'URDU', 'BENGALI', 'TAMIL', 'TELUGU', 'MARATHI', 'PUNJABI', 'UNKNOWN', name='language'), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('author_handle', sa.String(length=256), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('extracted_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('minhash_signature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['raw_events.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_events_is_processed', 'raw_events', ['is_processed'], unique=False)
    op.create_index('ix_raw_events_platform', 'raw_events', ['platform'], unique=False)
    op.create_index('ix_raw_events_published_at', 'raw_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_events_source_id'), 'raw_events', ['source_id'], unique=False)
    op.create_table('entity_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'event_id', name='uq_entity_event')
    )
    op.create_index(op.f('ix_entity_events_entity_id'), 'entity_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_events_event_id'), 'entity_events', ['event_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_type', sa.Enum('FINANCIAL_FRAUD', 'COORDINATED_INAUTHENTIC', 'KEYWORD_MATCH', 'ANOMALY_DETECTED', 'NETWORK_CLUSTER', 'PROPAGANDA', 'MILITARY_EVENT', 'PHISHING', 'SIM_SWAP', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'CONFIRMED', 'DISMISSED', 'ESCALATED', name='alertstatus'), nullable=True),
    sa.Column('trigger_event_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('matched_pattern', sa.String(length=256), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_alert_type'), 'risk_alerts', ['alert_type'], unique=False)
    op.create_index('ix_risk_alerts_created_at', 'risk_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_alerts_entity_id'), 'risk_alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_risk_level'), 'risk_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_alerts_risk_score'), 'risk_alerts', ['risk_score'], unique=False)
    op.create_index('ix_risk_alerts_risk_score_status', 'risk_alerts', ['risk_score', 'status'], unique=False)
    op.create_index(op.f('ix_risk_alerts_status'), 'risk_alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_alerts_status'), table_name='risk_alerts')
    op.drop_index('ix_risk_alerts_risk_score_status', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_risk_score'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_risk_level'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_entity_id'), table_name='risk_alerts')
    op.drop_index('ix_risk_alerts_created_at', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_alert_type'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_entity_events_event_id'), table_name='entity_events')
    op.drop_index(op.f('ix_entity_events_entity_id'), table_name='entity_events')
    op.drop_table('entity_events')
    op.drop_index(op.f('ix_raw_events_source_id'), table_name='raw_events')
    op.drop_index('ix_raw_events_published_at', table_name='raw_events')
    op.drop_index('ix_raw_events_platform', table_name='raw_events')
    op.drop_index('ix_raw_events_is_processed', table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_evidence_packages_entity_id'), table_name='evidence_packages')
    op.drop_table('evidence_packages')
    op.drop_index('ix_entity_aliases_value', table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_index('ix_entities_risk_score', table_name='entities')
    op.drop_index(op.f('ix_entities_risk_level'), table_name='entities')
    op.drop_index('ix_entities_primary_identifier', table_name='entities')
    op.drop_index(op.f('ix_entities_is_flagged'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
