"""Initial MVP database schema

Revision ID: 53ea09501c74
Revises: 
Create Date: 2026-05-08 15:36:10.601495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ea09501c74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_is_flagged'), 'entities', ['is_flagged'], unique=False)
    op.create_index('ix_entities_primary_identifier', 'entities', ['primary_identifier'], unique=False)
    op.create_index(op.f('ix_entities_risk_level'), 'entities', ['risk_level'], unique=False)
    op.create_index('ix_entities_risk_score', 'entities', ['risk_score'], unique=False)
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index('ix_entity_aliases_value', 'entity_aliases', ['alias_value'], unique=False)
    op.create_index(op.f('ix_entity_events_entity_id'), 'entity_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_events_event_id'), 'entity_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_evidence_packages_entity_id'), 'evidence_packages', ['entity_id'], unique=False)
    op.create_index('ix_raw_events_is_processed', 'raw_events', ['is_processed'], unique=False)
    op.create_index('ix_raw_events_platform', 'raw_events', ['platform'], unique=False)
    op.create_index('ix_raw_events_published_at', 'raw_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_raw_events_source_id'), 'raw_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_alert_type'), 'risk_alerts', ['alert_type'], unique=False)
    op.create_index('ix_risk_alerts_created_at', 'risk_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_alerts_entity_id'), 'risk_alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_risk_level'), 'risk_alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_alerts_risk_score'), 'risk_alerts', ['risk_score'], unique=False)
    op.create_index('ix_risk_alerts_risk_score_status', 'risk_alerts', ['risk_score', 'status'], unique=False)
    op.create_index(op.f('ix_risk_alerts_status'), 'risk_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_risk_alerts_status'), table_name='risk_alerts')
    op.drop_index('ix_risk_alerts_risk_score_status', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_risk_score'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_risk_level'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_entity_id'), table_name='risk_alerts')
    op.drop_index('ix_risk_alerts_created_at', table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_alert_type'), table_name='risk_alerts')
    op.drop_index(op.f('ix_raw_events_source_id'), table_name='raw_events')
    op.drop_index('ix_raw_events_published_at', table_name='raw_events')
    op.drop_index('ix_raw_events_platform', table_name='raw_events')
    op.drop_index('ix_raw_events_is_processed', table_name='raw_events')
    op.drop_index(op.f('ix_evidence_packages_entity_id'), table_name='evidence_packages')
    op.drop_index(op.f('ix_entity_events_event_id'), table_name='entity_events')
    op.drop_index(op.f('ix_entity_events_entity_id'), table_name='entity_events')
    op.drop_index('ix_entity_aliases_value', table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_index('ix_entities_risk_score', table_name='entities')
    op.drop_index(op.f('ix_entities_risk_level'), table_name='entities')
    op.drop_index('ix_entities_primary_identifier', table_name='entities')
    op.drop_index(op.f('ix_entities_is_flagged'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    # ### end Alembic commands ###
