"""add tables

Revision ID: d06fdb8072f3
Revises: 
Create Date: 2026-05-09 14:54:00.377621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'd06fdb8072f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure custom enums exist with correct values (lowercase, not native)
    op.execute("DROP TYPE IF EXISTS entitytype CASCADE")
    op.execute("DROP TYPE IF EXISTS alertstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS alerttype CASCADE")
    op.execute("DROP TYPE IF EXISTS risklevel CASCADE")
    
    op.execute("""CREATE TYPE entitytype AS ENUM (
        'person', 'phone', 'email', 'telegram', 'social_handle', 
        'upi_account', 'imei', 'crypto_wallet', 'organization', 
        'location', 'event', 'other'
    )""")
    op.execute("""CREATE TYPE alertstatus AS ENUM (
        'new', 'investigating', 'under_review', 'resolved', 'confirmed', 'dismissed'
    )""")
    op.execute("""CREATE TYPE alerttype AS ENUM (
        'suspicious_activity', 'malicious_intent', 'data_leak', 'financial_fraud',
        'coordinated_inauthentic', 'keyword_match', 'anomaly_detected', 
        'network_cluster', 'propaganda', 'other'
    )""")
    op.execute("""CREATE TYPE risklevel AS ENUM (
        'low', 'medium', 'high', 'critical'
    )""")
    
    op.create_table('entities',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('person', 'phone', 'email', 'telegram', 'social_handle', 'upi_account', 'imei', 'crypto_wallet', 'organization', 'location', 'event', 'other', name='entitytype', native_enum=False), nullable=False),
    sa.Column('primary_identifier', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel', native_enum=False), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('sentiment_avg', sa.Float(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('investigation_notes', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'primary_identifier', name='uq_entity_type_identifier')
    )
    op.create_index('idx_entity_risk_score', 'entities', ['risk_score'], unique=False)
    op.create_index('idx_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_table('keywords',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('risk_weight', sa.Float(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('sources',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('entity_id', UUID(), nullable=True),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('alias_value', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution_method', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'alias_type', 'alias_value', name='uq_entity_alias')
    )
    op.create_index('idx_alias_value', 'entity_aliases', ['alias_value'], unique=False)
    op.create_table('raw_events',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('source_id', UUID(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_language', sa.String(), nullable=True),
    sa.Column('translated_content', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('author_handle', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('matched_keywords', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of', UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['raw_events.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_events',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('entity_id', UUID(), nullable=True),
    sa.Column('event_id', UUID(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    op.create_table('users',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('risk_alerts',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('entity_id', UUID(), nullable=True),
    sa.Column('event_id', UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('suspicious_activity', 'malicious_intent', 'data_leak', 'financial_fraud', 'coordinated_inauthentic', 'keyword_match', 'anomaly_detected', 'network_cluster', 'propaganda', 'other', name='alerttype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('new', 'investigating', 'under_review', 'resolved', 'confirmed', 'dismissed', name='alertstatus', native_enum=False), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel', native_enum=False), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevel', native_enum=False), nullable=True),
    sa.Column('trigger_event_id', UUID(), nullable=True),
    sa.Column('matched_pattern', sa.String(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('assigned_to', UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_packages',
    sa.Column('id', UUID(), nullable=False),
    sa.Column('alert_id', UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['risk_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.drop_table('evidence_packages')
    op.drop_table('risk_alerts')
    op.drop_table('entity_events')
    op.drop_table('raw_events')
    op.drop_index('idx_alias_value', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_table('sources')
    op.drop_table('keywords')
    op.drop_index('idx_entity_type', table_name='entities')
    op.drop_index('idx_entity_risk_score', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
