// Mock data simulating Mythresh's generated data
export const MOCK_ALERTS = [
  {
    id: 'ALT-001',
    entity_name: 'Arjun Mehra',
    entity_type: 'Person',
    primary_id: '+91-9823456781',
    aliases: ['@arjun_m99', 'arjun.mehra@protonmail.com', '9823456781@upi'],
    alert_type: 'Coordinated Fraud Network',
    source: 'Telegram Public',
    source_tier: 1,
    risk_score: 9.2,
    sentiment: -0.87,
    status: 'new',
    timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
    summary: 'Coordinated UPI mule activity detected. 47 transactions/2h across 12 linked accounts. Matched Fraud Template #3 (layered transfers).',
    event_count: 47,
    flags: ['velocity_anomaly', 'pattern_match', 'negative_sentiment'],
    risk_factors: [
      'Transaction velocity anomaly (47 txns/2h)',
      'Matched Fraud Template #3 (UPI layering)',
      'Negative sentiment in 9/10 monitored posts',
    ],
  },
  {
    id: 'ALT-002',
    entity_name: 'SIM Cluster #7 — Rajasthan',
    entity_type: 'Phone_Cluster',
    primary_id: '+91-9711XXXXXX (x14)',
    aliases: ['SIM_swap_cluster_RJ', '@rj_finance_tips'],
    alert_type: 'SIM Swap Fraud Pattern',
    source: 'RSS: ANI News',
    source_tier: 2,
    risk_score: 8.7,
    sentiment: -0.72,
    status: 'under_review',
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    summary: '14 SIM cards registered within 3hr window, same Aadhaar cluster. Pattern matches SIM swap fraud template with 94% confidence.',
    event_count: 14,
    flags: ['sim_cluster', 'pattern_match', 'anomaly_detection'],
    risk_factors: [
      'SIM swap fraud pattern — 94% template match',
      'Anomaly: 14 SIM registrations / 3h (baseline: 0.2)',
      'Coordinated with 3 known flagged accounts',
    ],
  },
  {
    id: 'ALT-003',
    entity_name: 'Priya Shankar',
    entity_type: 'Person',
    primary_id: 'priya.shankar88@gmail.com',
    aliases: ['+91-8867543210', '@priya_sh88', 'priyashankar88@ybl'],
    alert_type: 'Inauthentic Influence Operation',
    source: 'Twitter/X',
    source_tier: 3,
    risk_score: 7.4,
    sentiment: -0.54,
    status: 'new',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    summary: 'Account part of coordinated inauthentic behavior cluster — 8 accounts posting identical content within 22-minute windows.',
    event_count: 8,
    flags: ['coordinated_behavior', 'inauthentic_content'],
    risk_factors: [
      'Coordinated inauthentic behavior (Jaccard sim: 0.91)',
      'Post frequency spike: 34 posts/hr (baseline: 2)',
      'Network centrality: top 5% in flagged subgraph',
    ],
  },
  {
    id: 'ALT-004',
    entity_name: 'hawala_network_UP',
    entity_type: 'SocialAccount',
    primary_id: '@hw_nets_up',
    aliases: ['hwala_nets_up@protonmail.com', '+91-9412XXXXXX'],
    alert_type: 'Keyword Alert: Hawala',
    source: 'Telegram Public',
    source_tier: 3,
    risk_score: 6.8,
    sentiment: -0.31,
    status: 'new',
    timestamp: new Date(Date.now() - 2.1 * 3600000).toISOString(),
    summary: 'Keyword "hawala" detected in 23 posts from this account in 48h. Cross-referenced with known hawala operator phone cluster.',
    event_count: 23,
    flags: ['keyword_match', 'hawala'],
    risk_factors: [
      'Keyword trigger: "hawala" (23 occurrences/48h)',
      'Phone cross-reference: linked to flagged cluster #12',
      'Source tier 3 — unverified channel, reduced multiplier',
    ],
  },
  {
    id: 'ALT-005',
    entity_name: 'Deepak Rao',
    entity_type: 'Person',
    primary_id: '+91-7756432109',
    aliases: ['deepak.rao@outlook.com', 'deepakrao@paytm', '@dr_finance_in'],
    alert_type: 'Phishing Domain Cluster',
    source: 'RSS: NDTV',
    source_tier: 1,
    risk_score: 5.9,
    sentiment: -0.19,
    status: 'confirmed',
    timestamp: new Date(Date.now() - 5.4 * 3600000).toISOString(),
    summary: 'Entity linked to 4 newly registered domains mimicking SBI and HDFC Bank portals. OCR extracted phishing content from shared images.',
    event_count: 4,
    flags: ['phishing', 'domain_cluster', 'ocr_detected'],
    risk_factors: [
      'Phishing domain cluster — 4 domains flagged',
      'OCR: extracted bank credentials form from image',
      'Domain registration burst: 4 domains / 6h',
    ],
  },
  {
    id: 'ALT-006',
    entity_name: 'Crypto-UPI Bridge Node #3',
    entity_type: 'UPIAccount',
    primary_id: 'cryptonode3@upi',
    aliases: ['+91-9900XXXXXX', '@crypt0_bridge_IN'],
    alert_type: 'Crypto-to-UPI Layering',
    source: 'Mock Data',
    source_tier: 2,
    risk_score: 8.1,
    sentiment: -0.61,
    status: 'new',
    timestamp: new Date(Date.now() - 7 * 3600000).toISOString(),
    summary: 'Central node in crypto-to-UPI layering network. ₹14.7L transacted through this node in 72h, split across 31 endpoints.',
    event_count: 31,
    flags: ['crypto_layering', 'velocity_anomaly', 'network_centrality'],
    risk_factors: [
      'Crypto-to-UPI layering: ₹14.7L / 72h',
      'Network centrality: 31 downstream endpoints',
      'Anomaly score: 0.96 (Isolation Forest)',
    ],
  },
];

export const MOCK_SOURCES = [
  { id: 'src-1', name: 'Telegram Public Channels', type: 'telegram', status: 'active', tier: 3, events_today: 312, last_crawl: new Date(Date.now() - 4 * 60000).toISOString() },
  { id: 'src-2', name: 'RSS: ANI News', type: 'rss', status: 'active', tier: 1, events_today: 89, last_crawl: new Date(Date.now() - 6 * 60000).toISOString() },
  { id: 'src-3', name: 'RSS: NDTV India', type: 'rss', status: 'active', tier: 1, events_today: 74, last_crawl: new Date(Date.now() - 5 * 60000).toISOString() },
  { id: 'src-4', name: 'Twitter/X Monitor', type: 'social', status: 'active', tier: 3, events_today: 201, last_crawl: new Date(Date.now() - 2 * 60000).toISOString() },
  { id: 'src-5', name: 'Mock Data Generator', type: 'mock', status: 'active', tier: 2, events_today: 500, last_crawl: new Date(Date.now() - 10 * 60000).toISOString() },
];

export const MOCK_KEYWORDS = [
  { id: 'kw-1', word: 'hawala', group: 'Financial Crime', hits_today: 23, enabled: true },
  { id: 'kw-2', word: 'SIM swap', group: 'Identity Fraud', hits_today: 7, enabled: true },
  { id: 'kw-3', word: 'mule account', group: 'Financial Crime', hits_today: 11, enabled: true },
  { id: 'kw-4', word: 'phishing', group: 'Cyber Crime', hits_today: 34, enabled: true },
  { id: 'kw-5', word: 'fake Aadhaar', group: 'Identity Fraud', hits_today: 4, enabled: true },
  { id: 'kw-6', word: 'dark web', group: 'Cyber Crime', hits_today: 9, enabled: false },
];

export const MOCK_GRAPH = {
  nodes: [
    { id: 'n1', label: 'Arjun Mehra', type: 'Person', risk: 9.2 },
    { id: 'n2', label: '+91-9823456781', type: 'Phone', risk: 8.1 },
    { id: 'n3', label: '@arjun_m99', type: 'SocialAccount', risk: 6.3 },
    { id: 'n4', label: '9823456781@upi', type: 'UPIAccount', risk: 7.8 },
    { id: 'n5', label: 'Rakesh Kumar', type: 'Person', risk: 7.1 },
    { id: 'n6', label: '+91-9711234560', type: 'Phone', risk: 5.4 },
    { id: 'n7', label: 'cryptonode3@upi', type: 'UPIAccount', risk: 8.1 },
    { id: 'n8', label: 'Suresh Patel', type: 'Person', risk: 4.2 },
  ],
  edges: [
    { source: 'n1', target: 'n2', relation: 'OWNS' },
    { source: 'n1', target: 'n3', relation: 'CONTROLS' },
    { source: 'n1', target: 'n4', relation: 'OWNS' },
    { source: 'n5', target: 'n6', relation: 'OWNS' },
    { source: 'n4', target: 'n7', relation: 'TRANSFERRED_TO' },
    { source: 'n5', target: 'n4', relation: 'TRANSFERRED_TO' },
    { source: 'n8', target: 'n6', relation: 'KNOWS' },
    { source: 'n8', target: 'n7', relation: 'TRANSFERRED_TO' },
  ]
};

export const DASHBOARD_STATS = {
  total_entities: 512,
  alerts_today: 43,
  high_risk_entities: 17,
  sources_active: 5,
  alerts_per_hour: [2,1,3,5,2,4,8,11,7,9,6,4,3,2,5,7,9,13,8,6,4,3,7,5],
};
